version: '3'

networks:
  scorpio-wu:
    name: scorpio-wu
    driver: bridge

services:
#  config-server:
#    container_name: config-server
#    image: zhazy/config-server:0.0.1-SNAPSHOT
#    ports:
#      - 8888:8888
  eureka-server:
    container_name: eureka-server
    image: zhazy/eureka-server:1.0.2-SNAPSHOT
    ports:
      - 8761:8761
    restart: always
    networks:
      - scorpio-wu
  cloud-gateway:
    container_name: cloud-gateway
    image: zhazy/cloud-gateway:1.0.2-SNAPSHOT
    ports:
      - 8080:8080
    restart: always
    networks:
      - scorpio-wu