server:
  port: 8091
spring:
  datasource:
    # Change DESKTOP-F879KH9 to your SQL server name
    url: jdbc:sqlserver://LAPTOP-UUTBA72E;encrypt=true;trustServerCertificate=true;databaseName=auth_service_database
    username: sa
    password: 1
